Repository slaclab/rogue, pull requests merged in 2022-03, with the labels that each got.

#856 ESROGUE-549: Update usingTcp.rst
  docs/src/interfaces/stream/usingTcp.rst
Labels: documentation

#845 Write only the stale part of a Block
  src/rogue/interfaces/memory/Block.cpp
Labels: bug

#857 Changes to provide easy access to examples without a git clone.
  conda-recipe-e3/meta.yaml
  conda-recipe/meta.yaml
  conda.yml
  conda_mac.yml
  notebooks/ExampleRoot.ipynb
  python/pyrogue/_Root.py
  python/pyrogue/examples/_AxiVersion.py
  python/pyrogue/examples/_ExampleRoot.py
  python/pyrogue/examples/_LargeDevice.py
  python/pyrogue/examples/__init__.py
  python/pyrogue/examples/__main__.py
  python/pyrogue/pydm/data_plugins/rogue_plugin.py
  python/pyrogue/pydm/examples/rogue_plugin_test.ui
  python/pyrogue/pydm/widgets/__init__.py
  python/pyrogue/pydm/widgets/designer.py
  python/pyrogue/pydm/widgets/plot.py
  templates/setup.py.in
Labels: enhancement

#858 Apply style sheet rule centrally on RogueLineEdit
  python/pyrogue/pydm/pydmTop.py
  python/pyrogue/pydm/widgets/line_edit.py
Labels: enhancement

#853 ESROGUE-569 - Add function to dump entire tree including Variable attributes to dict
  python/pyrogue/_Command.py
  python/pyrogue/_Memory.py
  python/pyrogue/_Node.py
  python/pyrogue/_Root.py
  python/pyrogue/_Variable.py
Labels: enhancement
