Repository slaclab/rogue, pull requests merged in 2022-02, with the labels that each got.

#838 ESROGUE-508: Reset RSSI counters in UdpRssiPack on Root.CountReset() Command
  include/rogue/protocols/rssi/Client.h
  include/rogue/protocols/rssi/Controller.h
  include/rogue/protocols/rssi/Server.h
  python/pyrogue/protocols/_Network.py
  src/rogue/protocols/rssi/Client.cpp
  src/rogue/protocols/rssi/Controller.cpp
  src/rogue/protocols/rssi/Server.cpp
Labels: enhancement

#839 ESROGUE-545: Disable Load and Save buttons in GUI when file text fields are blank
  python/pyrogue/pydm/widgets/root_control.py
Labels: enhancement

#843 Update petalinux.rst
  docs/src/installing/petalinux.rst
Labels: documentation

#836 ESROGUE-532: Bug fix for bad weak_ptr when calling shared_from_this()
  include/rogue/hardware/axi/AxiStreamDma.h
  include/rogue/hardware/pgp/PgpCard.h
  include/rogue/protocols/udp/Client.h
  include/rogue/protocols/udp/Server.h
  src/rogue/hardware/axi/AxiStreamDma.cpp
  src/rogue/hardware/pgp/PgpCard.cpp
  src/rogue/protocols/udp/Client.cpp
  src/rogue/protocols/udp/Server.cpp
Labels: bug

#844 ESROGUE-526: Use portable format specifiers when printing inttypes
  include/rogue/interfaces/stream/FrameAccessor.h
  src/rogue/Logging.cpp
  src/rogue/Version.cpp
  src/rogue/hardware/MemMap.cpp
  src/rogue/hardware/axi/AxiMemMap.cpp
  src/rogue/hardware/axi/AxiStreamDma.cpp
  src/rogue/hardware/pgp/PgpCard.cpp
  src/rogue/interfaces/ZmqClient.cpp
  src/rogue/interfaces/ZmqServer.cpp
  src/rogue/interfaces/memory/Block.cpp
  src/rogue/interfaces/memory/Emulate.cpp
  src/rogue/interfaces/memory/Master.cpp
  src/rogue/interfaces/memory/TcpClient.cpp
  src/rogue/interfaces/memory/TcpServer.cpp
  src/rogue/interfaces/memory/Transaction.cpp
  src/rogue/interfaces/stream/Buffer.cpp
  src/rogue/interfaces/stream/Filter.cpp
  src/rogue/interfaces/stream/Frame.cpp
  src/rogue/interfaces/stream/Pool.cpp
  src/rogue/interfaces/stream/Slave.cpp
  src/rogue/interfaces/stream/TcpCore.cpp
  src/rogue/protocols/batcher/CoreV1.cpp
  src/rogue/protocols/epicsV3/Server.cpp
  src/rogue/protocols/epicsV3/Value.cpp
  src/rogue/protocols/epicsV3/Variable.cpp
  src/rogue/protocols/packetizer/Controller.cpp
  src/rogue/protocols/packetizer/ControllerV1.cpp
  src/rogue/protocols/packetizer/ControllerV2.cpp
  src/rogue/protocols/rssi/Controller.cpp
  src/rogue/protocols/rssi/Header.cpp
  src/rogue/protocols/srp/SrpV0.cpp
  src/rogue/protocols/srp/SrpV3.cpp
  src/rogue/protocols/udp/Client.cpp
  src/rogue/protocols/udp/Core.cpp
  src/rogue/protocols/udp/Server.cpp
  src/rogue/utilities/Prbs.cpp
  src/rogue/utilities/StreamUnZip.cpp
  src/rogue/utilities/StreamZip.cpp
  src/rogue/utilities/fileio/LegacyStreamReader.cpp
  src/rogue/utilities/fileio/LegacyStreamWriter.cpp
  src/rogue/utilities/fileio/StreamReader.cpp
  src/rogue/utilities/fileio/StreamWriter.cpp
Labels: bug

#847 Add value and valueDisp to node information
  python/pyrogue/_Variable.py
  python/pyrogue/pydm/tools/node_info_tool.py
Labels: enhancement

#849 ESROGUE-506 - Revert changes to clean API in _Variable.py
  python/pyrogue/_Variable.py
  python/pyrogue/pydm/tools/node_info_tool.py
Labels: enhancement

#851 ESROGUE-536 - Fix negative values for file size in the GUI
  include/rogue/utilities/fileio/StreamWriter.h
  python/pyrogue/pydm/widgets/data_writer.py
Labels: bug

#850 Add `running` flag to `Device` to check whether `_start()` has been called
  python/pyrogue/_DataReceiver.py
  python/pyrogue/_Device.py
Labels: enhancement
