Repository slaclab/rogue, pull requests merged in 2024-01, with the labels that each got.

#976 Docker context that uses Anaconda to build rogue
  .github/workflows/rogue_ci.yml
  docker/rogue-anaconda/Dockerfile
  docker/rogue/Dockerfile
Labels: enhancement

#983 Fix nodeList method in Node and add global node count tracking
  python/pyrogue/_Node.py
Labels: bug, enhancement

#984 Fix bug in Device.setPollInterval()
  docs/src/migration/rogue_v6.rst
  python/pyrogue/_Device.py
Labels: bug, documentation
