Repository slaclab/rogue, pull requests merged in 2025-04, with the labels that each got.

#1060 Disable verify if overlapping variable is RO, WO or has verify disabled
  include/rogue/interfaces/memory/Block.h
  src/rogue/interfaces/memory/Block.cpp
Labels: enhancement

#1065 Disable append mode in file writer
  src/rogue/utilities/fileio/StreamWriter.cpp
Labels: enhancement

#1062 updating UdpRssiPack to updating the RSSI configuration before the RSSI connection is started
  python/pyrogue/protocols/_Network.py
Labels: enhancement

#1049 ESROGUE-699 - Support (u)int8 and (u)int16 Block numpy array access
  CMakeLists.txt
  docs/src/custom_module/makefile.rst
  src/rogue/interfaces/memory/Block.cpp
  tests/test_list_memory.py
Labels: enhancement

#1067 Add PRBS software transmit rate limit
  include/rogue/utilities/Prbs.h
  python/pyrogue/utilities/prbs.py
  src/rogue/utilities/Prbs.cpp
Labels: enhancement

#1064 Update operation of local variables
  python/pyrogue/_Block.py
  python/pyrogue/_Process.py
  python/pyrogue/_RunControl.py
  python/pyrogue/_Variable.py
  tests/test_localvars.py
Labels: bug, enhancement

#1066 Don't allow default set to RO register to result in stale state
  src/rogue/interfaces/memory/Block.cpp
  tests/test_enum.py
  tests/test_memory.py
Labels: bug

#1069 collections.Iterable -> collections.abc.Iterable
  .github/workflows/rogue_ci.yml
  CMakeLists.txt
  patches/epics.patch
  python/pyrogue/_Device.py
  python/pyrogue/_Node.py
  python/pyrogue/_Variable.py
  tests/test_epics.py
  tests/test_server.py
Labels: bug
